# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Install Geth (Go Ethereum) and tools
description: Installs Geth (Go Ethereum) and tools (abigen, bootnode, clef, evm, rlpdump) into your actions workflow

inputs:
  version:
    description: Geth version
    required: true
    default: latest
  github-token:
    description: GitHub auth token. Since there's a default, this is typically not supplied by the user
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js

branding:
  icon: download
  color: purple
